### ISSUE TITLE
コントラクト：`_contractURIHash` を準備する

### ISSUE THREAD

**Issue by yawn-c111** [MedicalDAO-dev/MedicalDAO#34]
- [x] バナー画像をIPFSにアップロードする
- [x] ドメインを取得する
- [ ] IPFSにコントラクトURIのJSONをアップロードする
- [ ] IPFSのCIDをトークンのsolファイルにハードコーディングする

**Comment by web3doctor** [comment]
![MedicalDAO ロゴ](https://github.com/MedicalDAO-dev/MedicalDAO/assets/115598921/7533af8d-bbcd-4f35-88a3-4955770f2f88)
こちらでお願いします

**Comment by yawn-c111** [comment]
@web3doctor 
ありがとうございます！！！
大変助かります！！
保存しました:pray:

**Comment by yawn-c111** [comment]
実装完了

条件整い次第、PRマージ
https://github.com/MedicalDAO-dev/MedicalDAO/pull/106
