### ISSUE TITLE
リーガルチェック

### ISSUE THREAD

**Issue by keit0728** [MedicalDAO-dev/MedicalDAO#89]

**Comment by web3doctor** [comment]
- 議決権→暗号資産該当性はない、故に金商法の定める暗号資産交換業も必要ない
    - 決済手段として使えるかが前提にある（もっとも重要）
        - 使えないので大丈夫
    - その上で量（金融庁ガイドライン）
        - 現状は無限発行だが1年で365議決のみなので大丈夫そう
    - その上で価格（金融庁ガイドライン）
        - 日本円換算で1000円以上となる
- MED→暗号資産に該当するかもしれないが、該当したとしても大丈夫そう（以下）
    - 前提の確認
        - 一人の保有量
            - 1000とか、10000とか
        - ユーティリティ
            - 労務の対価の用途
            - 議決権の購入の用途
                - 議決権自体に暗号資産該当性がないので大丈夫
            - 他の暗号資産を対価として配らなければOK
            - 売買できないならOK
            - 他の暗号資産と交換できなければOK
        - 獲得の仕方
            - 現金で買えない
            - 最初の流通は無償配布からの獲得（エアドロ）
            - そのあとはコミュニティの中での貢献や役務の対価として獲得
                
                
            - 上記満たせて入れば大丈夫だろう
    - 前払い式決済手段にも該当しないだろう
- PJからの収益をDAOトレジャリーに徴収する仕組み（下図「収益」、「予算」）
    - 前提
        - ①議決権持ってる人にPJで上がった収益を分配することはしない
        - ②議決権を持ってる人で談合して自分のPJ名義で資産を受け取れる可能性ある
    - 典型的な集団投資スキームではないが、該当する可能性がある→「収益」「予算」に関してはリーガルはっきりするまで避けた方が無難。
        - 典型的な集団投資スキームでない理由
            - 収益の分配が約束されていない点
- 利用規約
    - 決済手段ではないこと
    - 決済手段として今後も使わないことを明記する
    - 他の項目
        - NFT購入時の免責事項（オークション制であること、bidやtransfar失敗の可能性もあること）
        - NFTでできること（投票ルール、MEDによりVoting Powerが上昇するロジック）
        - houseルール（Discordでのコミュニケーションルール、Proposalを医療関係のトピックに限定するお願い等）
        - コントラクト変更の可能性とその方法
- 医療データと個人情報→実装する場合は整理する必要がある
![MedicalDAOスキーム](https://github.com/MedicalDAO-dev/MedicalDAO/assets/115598921/7f8a7f4d-787e-473e-af28-9c8db564ff71)

**Comment by web3doctor** [comment]
グレーゾーン解消制度に進むかはさらに詳細な検討が必要。
プロジェクトへの予算配分が典型的ではないが集団投資スキームに当たらないかどうか
・一社の方で知り合いの弁護士に上記チェックいただき、クリーンな形に修正する
・NounsやPNounsのPJ手掛けている人にコンタクト取る
・uwaizumiさんが関わるlegal DAOに相談する
・別の手法、ロジックを考える
解決策は上記かなと

**Comment by keit0728** [comment]
▼弁護士さんお打ち合わせ結果
投票権購入で集めた資金をプールしておいて予算配分する形式が、集団投資スキームになる可能性が一部ある
→これを精査するとかなりの費用がかかってしまう予定で、一社の弁護士さんとお話しするか、RM DAOで相談するか、技術的に回避する形か、pNounsにお伺いする形でなんとかしたい
配当が明確ではないけれども、もしかすると…。というレベル
Rulemakers DAOに上泉から確認する形でFix

https://cerulean-flannel-4b5.notion.site/mtg-6714e12a33d3410d87f327f1433830bd?pvs=4
弁護士との打ち合わせ議事録です。
